### ISSUE TITLE
其他平台支持

### ISSUE THREAD

**Issue by jason-mao** [VincentWei/minigui#23]
minigui如何支持一个FreeRTOS系统呢？ 是需要你们来支持，还是开发者也可以移植？

**Comment by VincentWei** [comment]
Technically, you can port MiniGUI to other RTOS by yourself. The code to support various RTOSes, such as uC/OS-II, VxWorks, ThreadX, and eCoS is already in the repository.

Here are some tips to port MiniGUI to a new RTOS:

- Define a global macro for your RTOS, for example: `__FREERTOS__`.
- Use MiniGUI-Standalone runtime mode to avoid using POSIX thread interfaces.
- Enable in-core resource support to avoid using file system.
- Use dummy NEWGAL and IAL engines for the first step.
- Disable some complex features such as support for FreeType and complex scripts.

Because most popular RTOSes now provide the basic support for POSIX interfaces, so the port will not be very difficult. However, you may need to implement some functions in MiniGUI for a specific RTOS. Please see the source file `src/misc/nposix.c`.
